### PR TITLE
ci: Add Python 3.8 to the CI Python matrix

### PR DESCRIPTION
**Pull request by matthewfeickert**
Now that [Python 3.8 has been added in the the `setup-python` GitHub Action](https://github.com/actions/setup-python/issues/30#issuecomment-549554778), it should be added to the Python runtime CI matrix.

### CODE REVIEW

**Comment by gordonwatts** [comment]
Well, shoot. A number of things over took this, so I'm going to have to do some merging back to get this branch working correctly. And see what has changed in 3.8.

**Comment by gordonwatts** [comment]
Ok - the 3.8 contains some real changes to how the AST is laid out. So for now I'll leave this here, and I will have to work on this once we get this into ServiceX.

**Comment by matthewfeickert** [comment]
> Ok - the 3.8 contains some real changes to how the AST is laid out. So for now I'll leave this here, and I will have to work on this once we get this into ServiceX.

Sounds good. This isn't needed, as you already merged `master` in, but to keep things easy to keep track of in the commit graph I'm just going to rebase this off of the main project's `master`.

**Comment by gordonwatts** [comment]
Closing this b.c. it is now very out of date. Due to `ast` changes, we are going to have to do some real work before moving to 3.8.

**Comment by matthewfeickert** [comment]
> Closing this b.c. it is now very out of date. Due to `ast` changes, we are going to have to do some real work before moving to 3.8.

Sounds good. Good news is that it is a trivial rebase whenever you get there, so I won't delete the branch. :)

**Pull request closed without merging**
