### PR TITLE
Parse Lambda's inline

### LINKED ISSUE #45: Add `lambda` source recovery
@AndrewEckart points out that recovering the `ast` from a `lambda` function isn't that difficult:

```
import inspect
import ast
sq_ast = ast.parse(inspect.getsource(lambda x: x*x))
lda = next((node for node in ast.walk(sq_ast)
                     if isinstance(node, ast.Lambda)), None)
if lda is None:
    # complain to user
```

## Motivation

This will make the source code look a lot nicer - rather than passing strings to `Select` one can now pass actual code - and further, it will allow editors and IDE's to syntax check at authorship time rather than just at run-time.

## Todo

- [x] Test inline `lambda` function
- [x] Test a function defined at global and local scope as an argument
- [x] Test nested lambda's in both cases
- [x] Update documentation

### PR DESCRIPTION
**Pull request by gordonwatts**
Add code to accept raw source code `lambda` in `Select` and `Where` statements.

- This relies on python's `inspect.source` library. At least in 3.7 and 3.6
- This is quite brittle. There are tests that look for problems in the way things are called.
- Exceptions with some text and source code are thrown when the `lambda` can't be determined.

The problem is that this can't do a more complex lambda function that inline the way we often see them in `func_adl`:

```python
def test_run_on_parse():
    'Emulate the syntax you often find when you have a multistep query'
    class my_obj:
        def do_it(self, x: Callable):
            parse_as_ast(x)
            return self

    # #&$&#^$^@ this parse error makes this almost not useful.
    with pytest.raises(Exception):
        long_expr = my_obj() \
            .do_it(lambda x: x + 1) \
            .do_it(lambda y: y + 2)
```

For this `inspect.getsource` returns:
```
'.do_it(lambda x: x + 1) \\\n            .do_it(lambda y: y + 2)'
```

which the ast parser totally fails at, obviously.

Really need a better way to look at where the lambda starts, exactly (is this in 3.8?).

Partial fixes #45

### CODE REVIEW

**Comment by gordonwatts** [comment]
@AndrewEckart  - any comments here?

**Comment by AndrewEckart** [comment]
Any implementation which relies on parsing source code is going to be somewhat fragile. That being said, here's a draft implementation which works for many common use cases:

```python
import ast
import inspect
from typing import Callable, Optional


def parse_as_ast(f: Callable) -> Optional[ast.Lambda]:
  source = inspect.getsource(f).strip()

  # Look for the name of the calling function (e.g. 'Select' or 'Where')
  caller_name = inspect.currentframe().f_back.f_code.co_name
  caller_idx = source.find(caller_name)
  # If found, parse the string between the parentheses of the function call
  if caller_idx > -1:
    source = source[caller_idx + len(caller_name):]
    i = 0
    open_count = 0
    while True:
      c = source[i]
      if c == '(':
        open_count += 1
      elif c == ')':
        open_count -= 1
      if open_count == 0:
        break
      i += 1
    source = source[:i+1]
  
  def parse(src: str) -> Optional[ast.Module]:
    try:
      return ast.parse(src)
    except SyntaxError:
      return None
  
  src_ast = parse(source)
  if not src_ast and source.endswith(')'):
    src_ast = parse(source[:-1])

  if not src_ast:
    return None

  lda = next((node for node in ast.walk(src_ast)
                    if isinstance(node, ast.Lambda)), None)

  if not lda:
    print('Could not find a lambda function')
    return None    

  return src_ast

```

Suppose we have a class definition like in your test case:
```python

class my_obj:

  def do_it(self, f: Callable):
    lda: ast.Lambda = parse_as_ast(f)
    return self
```

Here are some examples where this works:

```python
long_expr = my_obj() \
    .do_it(lambda x: x + 1) \
    .do_it(lambda y: y + 2)

other_expr = my_obj() \
  .do_it(
    lambda x: x + 1
  )

other_expr = my_obj() \
  .do_it(
    lambda x: x + 1)
```

Here's an example which breaks down because when we try parsing the second call to `do_it`, we find the first one instead, so we get the wrong lambda. This can probably be fixed, but the code might get a little messy. Alternately, we can give users a rule such as "one lambda per line".
```
long_expr = my_obj().do_it(lambda x: x + 1).do_it(lambda y: y + 2)
```

Here's a more complicated example from the docs which seems to work (modulo the two lambdas on one line issue above)

```
r = my_obj() \
    .do_it(lambda e: (e.Electrons("Electrons"), e.Muons("Muons"))) \
    .do_it(lambda ls: (ls[0].do_it(lambda e: e.pt()), \
                         ls[0].do_it(lambda e: e.eta()), \
                         ls[0].do_it(lambda e: e.phi()), \
                         ls[0].do_it(lambda e: e.e()), \
                         ls[1].do_it(lambda m: m.pt()), \
                         ls[1].do_it(lambda m: m.eta()), \
                         ls[1].do_it(lambda m: m.phi()), \
                         ls[1].do_it(lambda m: m.e())))
```

**Comment by AndrewEckart** [comment]
Another note: I don't think it's strictly necessary to define a subclass of `ast.NodeVisitor`. It seems like this is usually done when you want to modify the tree. In this case the custom NodeVisitor complains when more than one lambda is found, but there is actually a valid use case for nested lambdas. I'd stick with `next((node for node in ast.walk(src_ast)
                    if isinstance(node, ast.Lambda)), None)` - since `ast.walk` performs a breadth-first search, it will always find the outermost lambda if two are nested, which is what we want.

**Comment by gordonwatts** [comment]
This works really well! I'm going to put it in. I'm adding one more error catch case:

```
parse_as_ast(lambda x: x + 1), parse_as_ast(lambda y: y * 10)
```

that should throw (it currently succeeds silently, but parses the first lambda twice).

And then we can add something to look at more info if the python version is later than 3.7

**Pull request merged**
